import processing.core.*; 
import processing.data.*; 
import processing.event.*; 
import processing.opengl.*; 

import g4p_controls.*; 
import java.nio.file.FileSystems; 
import java.nio.file.Paths; 
import java.nio.file.Path; 
import java.nio.file.attribute.BasicFileAttributes; 
import java.nio.file.Files; 
import java.nio.file.attribute.FileTime; 
import java.io.File; 
import processing.sound.*; 
import javax.swing.JOptionPane; 
import java.awt.Component; 
import java.awt.Dimension; 
import java.awt.FlowLayout; 
import java.awt.event.WindowAdapter; 
import java.awt.event.WindowEvent; 
import javax.swing.JDialog; 
import javax.swing.JLabel; 
import javax.swing.JPanel; 
import javax.swing.JPasswordField; 
import javax.swing.JFrame; 
import java.io.IOException; 
import javax.swing.JRootPane; 
import javax.swing.JFrame; 
import processing.awt.PSurfaceAWT.SmoothCanvas; 
import com.sun.awt.AWTUtilities; 

import java.util.HashMap; 
import java.util.ArrayList; 
import java.io.File; 
import java.io.BufferedReader; 
import java.io.PrintWriter; 
import java.io.InputStream; 
import java.io.OutputStream; 
import java.io.IOException; 

public class ipwndfu_gui extends PApplet {

// Need G4P library


























boolean exploited = false;

public void setup() {
  
  createGUI();
  customGUI();
  // Place your setup code here
}

public void draw() {
  background(230);
  //strokeWeight(2);
  line(0, (height/2)-20, width, (height/2)-20);
  line((width/2)-60, (height/2)-20, (width/2)-60, height);
  //rect();
}

// Use this method to add additional statements
// to customise the GUI controls
public void customGUI() {
}

public void exploit() {
  exploited = true;
  try {
    exec("./ipwndfu -p");
  } 
  catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(null, ex + "\nMaybe this software is corrupted. re-download it.");
    exploited = false;
  }
}

public void boot() {
  if (exploited) {
    try {
      exec("./ipwndfu --boot ");
    } 
    catch (Exception ex) {
      javax.swing.JOptionPane.showMessageDialog(null, ex);
    }
  } else {
    notExploited();
  }
}
public void notExploited() {
  javax.swing.JOptionPane.showMessageDialog(null, "First you have to exploit the device!");
}

public void sendSelect() {
  javax.swing.JOptionPane.showMessageDialog(null, "Note: Big files can take a while to be sent"); 
  String selected = G4P.selectInput("Select a file to send to the device", "*", "File");
  if (exploited) {
    if (selected != null) {
      sendFile(selected);
    }
  } else {
    notExploited();
  }
}
public void sendFile(String file) {
  try {
    exec("./ipwndfu -f " + file);
  } 
  catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(null, ex);
  }
}

/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:520344:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  exploit();
} //_CODE_:button1:520344:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:774951:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  boot();
} //_CODE_:button2:774951:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:574246:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  sendSelect();
} //_CODE_:button3:574246:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("ipwndfu-GUI by Adryzz. Not for commercial use.");
  label1 = new GLabel(this, 160, 50, 270, 31);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("ipwndfu-GUI by Adryzz Not for commercial use.");
  label1.setOpaque(false);
  button1 = new GButton(this, 489, 147, 80, 30);
  button1.setText("Exploit!");
  button1.addEventHandler(this, "button1_click1");
  label2 = new GLabel(this, 55, 143, 418, 39);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Connect the Iphone in DFU mode and click on the exploit button.\nThen, use the exploit with the buttons below.");
  label2.setOpaque(false);
  button2 = new GButton(this, 62, 239, 80, 30);
  button2.setText("Boot");
  button2.addEventHandler(this, "button2_click1");
  label3 = new GLabel(this, 46, 281, 118, 30);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Boots in Verbose mode");
  label3.setOpaque(false);
  button3 = new GButton(this, 300, 240, 80, 30);
  button3.setText("Send file");
  button3.addEventHandler(this, "button3_click1");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GButton button1; 
GLabel label2; 
GButton button2; 
GLabel label3; 
GButton button3; 

  public void settings() {  size(640, 480); }
  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ipwndfu_gui" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
